### ISSUE TITLE
Status of this crate?

### ISSUE THREAD

**Issue by Geobert** [ruabmbua/hidapi-rs#20]
Hi,

I was wondering about the state of this crate as nothing happened for a year now.

Is it deprecated? Any alternative?

**Comment by Osspial** [comment]
I forked this crate from the original by @ruabmbua because I wanted to make some changes to fit my usecase and publish the changes to crates.io. However I was inexperienced with the open-source process, the original didn't seem to have much activity, and didn't want to wait for a PR to get merged/pushed to crates.io.

What I somehow didn't expect was that people would find issues with my code and then make changes to them! I lost the motivation to work on this crate pretty quickly after putting it on crates.io and (ironically enough) have left people waiting for PRs to get merged. I'm really sorry about that. That being said I'd be up for transferring control of this back to @ruabmbua and giving him control over the `crates.io` crate, as he seems to still be involved with its development.

**Comment by ruabmbua** [comment]
Hi @Geobert , I took over the crate now.

It will get a few updates & fixes, and a new mayor version.
