### ISSUE TITLE
Segfault on HidApi::new() when no HID devices are found.

### ISSUE THREAD

**Issue by kitlith** [ruabmbua/hidapi-rs#5]
If I am correct, something isn't checking if it's NULL in case there's no devices, so when it tries to move stuff from the non-existant CFFI struct into a native struct... it, well, segfaults.

If I understand correctly, all that needs to be done is add a NULL check to get_hid_device_info_vector, or restructure the loop slightly.

I may try to send a PR tomorrow, but first I must sleep.

**Comment by ruabmbua** [comment]
"NULL in the case of failure." says the hidapi manual. Their documentation is also slightly wrong, because no devices is indeed a possibility, but might be rare.

The rust wrapper should  check the case, but we have to decide what we want to return. I think changing the return signature to a Result might be the right choice if we want to interpret it exactly like the hidapi doc.

**Comment by kitlith** [comment]
I'm leaning towards an Option, given that we have no way to see if there are just none or if there was an error. That said, the final user will end up knowing if it's an error or not, given that there's a `printf("Can't create udev\n");` inside `hid_enumerate()`. >_> (At least, in the linux backend)

EDIT: Sorry, I'm still tired today. My thought is that `hid_enumerate()` returns Option, and `conv_hid_device_info()` can return Result if a NULL pointer is passed. `get_hid_device_info_vector` should be Option, I think, because after fixing the bug in the loop logic if `hid_enumerate()` returns NULL, the only real `error` can come from `hid_enumerate()`, which would be option for already mentioned reasons. At least, that's what I'm thinking in my head.

**Comment by 19h** [comment]
Let's be rusty about this: if `hid_enumerate()` returns NULL, we should return `None`. Result is a boolean operation -- either it works or it fails.

But if we're pragmatic, we should return an empty Iterator. That way, if one really needs to check for the length of the devices instead of matching a particular device, `api.devices().iter().collect::<Vec<&hidapi::HidDeviceInfo>>().len()` would do the job.

**Comment by r8d8** [comment]
Facing this issue on a laptop (ArchLinux), 
`hidapi` detects only one device, if I unplug it -> SeqFault.
Are there any work arounds?

**Comment by ruabmbua** [comment]
This should probably be fixed in the library. A workaround would be adding an extern "C" hid_enumerate() in your application. (You should look for the correct function prototype).

Then you can call it and if it returns a NULL pointer you should omit calling HidApi::new() or refresh_devices.

**Comment by ruabmbua** [comment]
I will create a PR today after work which will fix this issue.

**Comment by Osspial** [comment]
#9 closes this.
