### ISSUE TITLE
Consider changing the default Linux backend for hidraw to support Bluetooth

### ISSUE THREAD

**Issue by thomasgauthier** [ruabmbua/hidapi-rs#60]
The default features right now do not support Bluetooth devices on Linux which is unfortunate. Are there any stability/safety reasons for defaulting to libusb?

**Comment by ruabmbua** [comment]
I am using the hidraw interface myself all the time. When the library was originally created, I decided to stick with libusb because many linux distros had issues with hidraw at the time (there was a bug affecting some kernels).

I am not aware, if any of these affected versions are still in use. 

If you want you can send a PR to change the default backend, or maybe just add a note to the readme for people who are not aware about bluetooth support, when the kernel interface is used directly.
